### ISSUE TITLE
Problem finding geo collider.rb

### ISSUE THREAD

**Issue by Jmuccigr** [isawnyu/geocollider#20]
I'm not bundler/gem expert, but I ran into this problem today: running one of the included scripts (csv-csv), I got this error:

    Traceback (most recent call last):
	  2: from bin/geocollider-csv-csv.rb:8:in '<main>'
	  1: from /Users/john_muccigrosso/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in 'require':
    cannot load such file -- geocollider (LoadError)`

After a lot of on-line search, I found that if I added these lines to the script and did a `bundle update`, it worked

    require 'rubygems'
    require 'bundler/setup'

Again, not quite sure I'm doing this right.

**Comment by ryanfb** [comment]
It may be that you were running the command without `bundle exec`, e.g.:

    bundle exec ./bin/geocollider-csv-csv.rb csv1.csv csv2.csv out.csv

~~I can add the lines you suggest to the scripts to eliminate the need to wrap everything in `bundle exec`.~~

After trying it both ways on my own machine, it may have been that you were using `bundle exec` (which `require 'bundler/setup'` doesn't seem to remove the need for) but were possibly inside the `bin` directory, which is why it couldn't find the `geocollider` lib, and that adding `require 'bundler/setup'` will fix this.

**Comment by Jmuccigr** [comment]
I can check this later, but I did try the `bundle exec` command at some point in my testing. I don't remember which directory I was in though.

**Comment by Jmuccigr** [comment]
Yes, `bundle exec ./bin/whatever.rb` works when I'm in the geocollider dir within `~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/`

(Still not clear to me why GitHub-derived gems don't show up in `gem list`, but that's another issue.)
